### ISSUE TITLE
Try Setting Ollama again, same problem invalid key

### ISSUE THREAD

**Issue by yuchaozhou** [ryoppippi/curxy#21] opened 2024-09-23 06:01 UTC
## Local curl Test Result
```
curl https://modified-exist-preview-grant.trycloudflare.com/v1/chat/completions -H "Content-Type: applicati
on/json" -H "Authorization: Bearer sk-123456" -d '{
  "messages": [
    {
      "role": "system",
      "content": "You are a test assistant."
    },
    {
      "role": "user",
      "content": "Testing. Just say hi and nothing else."
    }
  ],
  "model": "qwen2.5-coder:7b"
}'
{"id":"chatcmpl-936","object":"chat.completion","created":1727070864,"model":"qwen2.5-coder:7b","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"Hi"},"finish_reason":"stop"}],"usage":{"prompt_tokens":28,"completion_tokens":2,"total_tokens":30}}
```
### Cursor Setting ok and try it Reuslt
![WX20240923-135653](https://github.com/user-attachments/assets/c74fa468-fa65-476f-be92-0cbc2c0ee48b)

### Cursor Setting Vefity Result
![WX20240923-135725](https://github.com/user-attachments/assets/9e9c35e3-aba3-47b5-8cb7-09ac3d1f56b1)

### jsr:@ryoppippi/curxy Version
deno info jsr:@ryoppippi/curxy
local: /Users/daliang/Library/Caches/deno/deps/https/jsr.io/950e3119340a11b204fe5b4a76d804870d26c0c30ba499041ec818653f071eaa
emit: /Users/daliang/Library/Caches/deno/gen/https/jsr.io/950e3119340a11b204fe5b4a76d804870d26c0c30ba499041ec818653f071eaa.js
type: TypeScript
dependencies: 177 unique
size: 1.47MB

https://jsr.io/@ryoppippi/curxy/0.1.8/main.ts (2.4KB)

## cursor version
Version: 0.41.2
VSCode Version: 1.91.1
Commit: 297991d169fa3a11975c5aa95adc69be73250c70
Date: 2024-09-21T04:18:39.370Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.1.0

## Ollama version
ollama version is 0.3.6

Please check this problem, THX Again!

**Comment by ryoppippi** [comment] 2024-09-25 10:16
Thanks. This is the duplicate of #20

**Closed by ryoppippi** 2024-09-25 10:16 UTC
